# Generated by Django 4.2.23 on 2025-08-06 15:52

import deals.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('agreement_code', models.CharField(max_length=250, verbose_name='Реквизиты договора')),
                ('agreement_date', models.DateTimeField(verbose_name='Дата договора')),
                ('agreement_type', models.PositiveSmallIntegerField(choices=[(1, 'Цессия'), (2, 'Аутсорсинг')], default=1, verbose_name='Тип')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('total_sum', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Стоимость портфеля')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Размер портфеля')),
                ('agreement_doc', models.FileField(max_length=1024, null=True, upload_to=deals.models.Agreement.agreement_doc_path, verbose_name='Документ')),
            ],
            options={
                'verbose_name': 'Договор',
                'verbose_name_plural': 'Договор',
                'db_table': 'agreement',
            },
        ),
        migrations.CreateModel(
            name='Creditor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('type', models.IntegerField(choices=[(1, 'Банк'), (2, 'МФКО'), (3, 'МКО')], verbose_name='Тип кредитора')),
                ('name', models.CharField(max_length=250, verbose_name='Наименование')),
                ('date_add', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'кредитора',
                'verbose_name_plural': 'Кредитор',
                'db_table': 'credit_creditor',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=250, verbose_name='Наименование')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Цессия')], default=1, verbose_name='Тип')),
                ('process_type', models.PositiveSmallIntegerField(choices=[(1, 'Юридический')], default=1, verbose_name='Тип работы')),
                ('total_sum', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Стоимость')),
                ('date_placement', models.DateField(default=django.utils.timezone.now, verbose_name='дата начала работы')),
                ('date_finish', models.DateField(blank=True, null=True, verbose_name='дата окончания работы')),
                ('cession_date', models.DateField(blank=True, null=True, verbose_name='Дата переуступки')),
                ('agreement', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='deals.agreement')),
            ],
            options={
                'verbose_name': 'портфель',
                'verbose_name_plural': 'Портфель',
                'db_table': 'credit_portfolio',
            },
        ),
        migrations.AddField(
            model_name='agreement',
            name='creditor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creditor', to='deals.creditor', verbose_name='Кредитор'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='creditor_first',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='creditor_first', to='deals.creditor', verbose_name='Первоначальный кредитор'),
        ),
    ]
