# Generated by Django 4.2.23 on 2025-08-07 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='label',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Наименование'),
        ),
    ]
