# Generated by Django 4.2.23 on 2025-08-07 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0002_alter_portfolio_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='agreement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='deals.agreement'),
        ),
    ]
