# Generated by Django 4.2.23 on 2025-08-07 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0003_alter_portfolio_agreement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='creditor_first',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creditor_first', to='deals.creditor', verbose_name='Первоначальный кредитор'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='agreement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deals.agreement'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='label',
            field=models.CharField(max_length=250, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='process_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Лигал'), (2, 'ИП'), (3, 'Хард'), (4, 'Софт'), (5, 'Изъятие'), (6, 'Банкротство'), (7, 'Фулл')], default=1, verbose_name='Тип работы'),
        ),
    ]
