# Generated by Django 4.2.23 on 2025-08-07 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0004_alter_agreement_creditor_first_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='creditor_first',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='creditor_first', to='deals.creditor', verbose_name='Первоначальный кредитор'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='agreement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='deals.agreement'),
        ),
    ]
