# Generated by Django 4.2.23 on 2025-08-07 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0005_alter_agreement_creditor_first_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ['id'], 'verbose_name': 'портфель', 'verbose_name_plural': 'Портфель'},
        ),
        migrations.AddField(
            model_name='portfolio',
            name='sequence_number',
            field=models.PositiveIntegerField(default=1, verbose_name='Порядковый номер портфеля'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='agreement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deals.agreement'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='label',
            field=models.CharField(blank=True, max_length=255, verbose_name='Наименование портфеля'),
        ),
    ]
