# Generated by Django 4.2.23 on 2025-08-07 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0006_alter_portfolio_options_portfolio_sequence_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'verbose_name': 'портфель', 'verbose_name_plural': 'Портфель'},
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='sequence_number',
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='agreement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='deals.agreement'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='label',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Наименование'),
        ),
    ]
